# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nlpost_gomp <- function(param, data) {
    .Call('iLaplaceExamples_nlpost_gomp', PACKAGE = 'iLaplaceExamples', param, data)
}

grad_gomp <- function(param, data) {
    .Call('iLaplaceExamples_grad_gomp', PACKAGE = 'iLaplaceExamples', param, data)
}

hess_gomp <- function(param, data) {
    .Call('iLaplaceExamples_hess_gomp', PACKAGE = 'iLaplaceExamples', param, data)
}

nlDen_mvt <- function(x, m, df) {
    .Call('iLaplaceExamples_nlDen_mvt', PACKAGE = 'iLaplaceExamples', x, m, df)
}

nlDen_mvskt <- function(x, a, c, m, df) {
    .Call('iLaplaceExamples_nlDen_mvskt', PACKAGE = 'iLaplaceExamples', x, a, c, m, df)
}

grad_mvt <- function(x, m, df) {
    .Call('iLaplaceExamples_grad_mvt', PACKAGE = 'iLaplaceExamples', x, m, df)
}

grad_mvskt <- function(x, a, c, m, df) {
    .Call('iLaplaceExamples_grad_mvskt', PACKAGE = 'iLaplaceExamples', x, a, c, m, df)
}

hess_mvt <- function(x, m, df) {
    .Call('iLaplaceExamples_hess_mvt', PACKAGE = 'iLaplaceExamples', x, m, df)
}

hess_mvskt <- function(x, a, c, m, df) {
    .Call('iLaplaceExamples_hess_mvskt', PACKAGE = 'iLaplaceExamples', x, a, c, m, df)
}

dmvt <- function(x, mu, S, p, df, lg) {
    .Call('iLaplaceExamples_dmvt', PACKAGE = 'iLaplaceExamples', x, mu, S, p, df, lg)
}

dhalfCauchy <- function(x, scale, lg = FALSE) {
    .Call('iLaplaceExamples_dhalfCauchy', PACKAGE = 'iLaplaceExamples', x, scale, lg)
}

rmvnorm <- function(mu, S, p) {
    .Call('iLaplaceExamples_rmvnorm', PACKAGE = 'iLaplaceExamples', mu, S, p)
}

rmvt <- function(mu, S, p, df) {
    .Call('iLaplaceExamples_rmvt', PACKAGE = 'iLaplaceExamples', mu, S, p, df)
}

prJeff <- function(nu, lg = FALSE) {
    .Call('iLaplaceExamples_prJeff', PACKAGE = 'iLaplaceExamples', nu, lg)
}

grldmvt <- function(x, mu, S, p, df) {
    .Call('iLaplaceExamples_grldmvt', PACKAGE = 'iLaplaceExamples', x, mu, S, p, df)
}

hessldmvt <- function(x, mu, S, p, df) {
    .Call('iLaplaceExamples_hessldmvt', PACKAGE = 'iLaplaceExamples', x, mu, S, p, df)
}

nlpost_lub <- function(beta, lsig, y, x1, x2, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplaceExamples_nlpost_lub', PACKAGE = 'iLaplaceExamples', beta, lsig, y, x1, x2, n, muBeta, SigBeta, sigScale)
}

nlpostT_lub <- function(beta, lsig, lnu, y, x1, x2, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplaceExamples_nlpostT_lub', PACKAGE = 'iLaplaceExamples', beta, lsig, lnu, y, x1, x2, n, muBeta, SigBeta, sigScale)
}

grad_lub <- function(beta, lsig, y, x1, x2, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplaceExamples_grad_lub', PACKAGE = 'iLaplaceExamples', beta, lsig, y, x1, x2, n, muBeta, SigBeta, sigScale)
}

gradT_lub <- function(beta, lsig, lnu, y, x1, x2, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplaceExamples_gradT_lub', PACKAGE = 'iLaplaceExamples', beta, lsig, lnu, y, x1, x2, n, muBeta, SigBeta, sigScale)
}

hess_lub <- function(beta, lsig, y, x1, x2, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplaceExamples_hess_lub', PACKAGE = 'iLaplaceExamples', beta, lsig, y, x1, x2, n, muBeta, SigBeta, sigScale)
}

hessT_lub <- function(beta, lsig, lnu, y, x1, x2, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplaceExamples_hessT_lub', PACKAGE = 'iLaplaceExamples', beta, lsig, lnu, y, x1, x2, n, muBeta, SigBeta, sigScale)
}

MCMCmetrop_cpp <- function(lfun, start, V, mcmc, burnin, df, verbose, myframe) {
    .Call('iLaplaceExamples_MCMCmetrop_cpp', PACKAGE = 'iLaplaceExamples', lfun, start, V, mcmc, burnin, df, verbose, myframe)
}

mlChib_cpp <- function(lfun, hatPar, V, mcmc, df, verbose, myframe) {
    .Call('iLaplaceExamples_mlChib_cpp', PACKAGE = 'iLaplaceExamples', lfun, hatPar, V, mcmc, df, verbose, myframe)
}

mlIS_cpp <- function(lfun, hatPar, V, nsim, p, df, verbose, myframe) {
    .Call('iLaplaceExamples_mlIS_cpp', PACKAGE = 'iLaplaceExamples', lfun, hatPar, V, nsim, p, df, verbose, myframe)
}

nlpost_bod2 <- function(beta, lsig, y, x, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplaceExamples_nlpost_bod2', PACKAGE = 'iLaplaceExamples', beta, lsig, y, x, n, muBeta, SigBeta, sigScale)
}

nlpostT_bod2 <- function(beta, lsig, lnu, y, x, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplaceExamples_nlpostT_bod2', PACKAGE = 'iLaplaceExamples', beta, lsig, lnu, y, x, n, muBeta, SigBeta, sigScale)
}

grad_bod2 <- function(beta, lsig, y, x, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplaceExamples_grad_bod2', PACKAGE = 'iLaplaceExamples', beta, lsig, y, x, n, muBeta, SigBeta, sigScale)
}

hess_bod2 <- function(beta, lsig, y, x, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplaceExamples_hess_bod2', PACKAGE = 'iLaplaceExamples', beta, lsig, y, x, n, muBeta, SigBeta, sigScale)
}

gradT_bod2 <- function(beta, lsig, lnu, y, x, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplaceExamples_gradT_bod2', PACKAGE = 'iLaplaceExamples', beta, lsig, lnu, y, x, n, muBeta, SigBeta, sigScale)
}

hessT_bod2 <- function(beta, lsig, lnu, y, x, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplaceExamples_hessT_bod2', PACKAGE = 'iLaplaceExamples', beta, lsig, lnu, y, x, n, muBeta, SigBeta, sigScale)
}

nlpost_rebin <- function(u, theta, y, n) {
    .Call('iLaplaceExamples_nlpost_rebin', PACKAGE = 'iLaplaceExamples', u, theta, y, n)
}

grU_rebin <- function(u, theta, y, n) {
    .Call('iLaplaceExamples_grU_rebin', PACKAGE = 'iLaplaceExamples', u, theta, y, n)
}

hessU_rebin <- function(u, theta, y, n) {
    .Call('iLaplaceExamples_hessU_rebin', PACKAGE = 'iLaplaceExamples', u, theta, y, n)
}

